import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Tracking Server',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased text-md`}>{children}</body>
    </html>
  )
}
