### Create a location

POST http://localhost:3000/api/locations
Content-Type: application/json
X-Tracker-Secret: {{$dotenv MOBILE_REQUEST_SECRET}}

{
  "uniqueId": "123",
  "latitude": 74.23423,
  "longitude": 74.23423,
  "source": "yo-mama"
}

### Create a batch of locations

POST http://localhost:3000/api/locations/batch
Content-Type: application/json
X-Tracker-Secret: {{$dotenv MOBILE_REQUEST_SECRET}}

{
  "locations": [
    {
      "uniqueId": "123123",
      "latitude": 74.23423,
      "longitude": 74.23423,
      "source": "yo-mama"
    },
    {
      "uniqueId": "broobrobor",
      "latitude": 74.23423,
      "longitude": 74.23423,
      "source": "yo-mama"
    }
  ]
}